name: Update README

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update in README (without v prefix)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README.md
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/}
            VERSION=${VERSION#v}
          fi
          echo "Updating README.md for version ${VERSION}"
          sed -i "/### Download Binary/,/### Manual Installation/c\### Download Binary\n\nChoose the appropriate version for your system:\n\n| Platform | Architecture | Download |\n|----------|-------------|----------|\n| Windows | x64 | [Download](https://github.com/${{ github.repository }}/releases/download/v${VERSION}/ariaj_${VERSION}_Windows_x86_64.zip) |\n| Windows | ARM64 | [Download](https://github.com/${{ github.repository }}/releases/download/v${VERSION}/ariaj_${VERSION}_Windows_arm64.zip) |\n| Linux | x64 | [Download](https://github.com/${{ github.repository }}/releases/download/v${VERSION}/ariaj_${VERSION}_Linux_x86_64.tar.gz) |\n| Linux | ARM64 | [Download](https://github.com/${{ github.repository }}/releases/download/v${VERSION}/ariaj_${VERSION}_Linux_arm64.tar.gz) |\n| macOS | x64 | [Download](https://github.com/${{ github.repository }}/releases/download/v${VERSION}/ariaj_${VERSION}_Darwin_x86_64.tar.gz) |\n| macOS | ARM64 | [Download](https://github.com/${{ github.repository }}/releases/download/v${VERSION}/ariaj_${VERSION}_Darwin_arm64.tar.gz) |\n\n[View all releases](https://github.com/${{ github.repository }}/releases)\n\n### Manual Installation" README.md

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update download links for version ${GITHUB_REF#refs/tags/}"
          title: "docs: update download links for latest release"
          body: "Auto-generated PR to update download links in README.md for the latest release"
          branch: "auto-readme"
